apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-frontend-deployment
  labels:
    app: demo-frontend
spec:
  replicas: 2 # Number of pod replicas
  selector:
    matchLabels:
      app: demo-frontend
  template:
    metadata:
      labels:
        app: demo-frontend
    spec:
      containers:
      - name: demo-frontend
        image: ghcr.io/octopussolutionsengineering/octopus-zero-to-hero/demo-frontend:2024.10.21.19 # Replace with your container image
        ports:
        - containerPort: 80 # Port exposed by the container (matches the Dockerfile)
        env:
        - name: WELCOME_MESSAGE
          value: "Welcome to the Octopus Zero to Hero Webinar!" # Example environment variable
        - name: FOOTER_TEXT
          value: "Powered by Kubernetes and Octopus Deploy"
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 20

---
apiVersion: v1
kind: Service
metadata:
  name: demo-frontend-service
  labels:
    app: demo-frontend
spec:
  type: NodePort # Use NodePort for local access
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: demo-frontend
