name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Docker Buildx (for building multi-platform images if needed)
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Step 3: Log in to the GitHub container registry
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    # Step 4: Get the current date in YYYY.MM.DD format and append the GitHub run number
    - name: Get Date and Build Run Number for version tag
      id: version
      run: echo "::set-output name=tag::$(date +'%Y.%m.%d').${{ github.run_number }}"

    # Step 5: Build and tag the Docker image
    - name: Build the Docker image
      run: |
        docker build -t ghcr.io/${{ github.repository }}/demo-frontend:${{ steps.version.outputs.tag }} -f demo-frontend/Dockerfile .
    
    # Step 6: Push the Docker image to GitHub Container Registry
    - name: Push the Docker image
      run: |
        docker push ghcr.io/${{ github.repository }}/demo-frontend:${{ steps.version.outputs.tag }}
